### ISSUE TITLE
Don't know how to make it accept custom items

### ISSUE THREAD

**Issue by Aweguy** [abluescarab/tModLoader-CustomSlot#1]
How can i make it accept only a custom type of items i have made named 'Flair'? I have tried everything but couldn't do it alone. Could you help? I have also contacted you on discord.

**Comment by abluescarab** [comment]
Let me know if the methods we discussed on Discord work.

**Comment by Aweguy** [comment]
I contacted you via discord for my problems. Sorry for bothering again. I am definately doing something wrong in both of my problems even if you have told me what to do. I have sent all codes for that (except the mod.cs).

**Comment by abluescarab** [comment]
I believe we worked this out back when this issue was made. Please open a separate issue if you run into any other problem, or post in the discussions board on this repository.
