### ISSUE TITLE
ModContent.GetTexture problem

### ISSUE THREAD

**Issue by Khotul** [abluescarab/tModLoader-CustomSlot#2]
Not really an issue, because I've managed to solve it myself, but I wanted to share my solution, in case someone encountered the same issue.

In this tutorial, there's this part `ModContent.GetInstance<MyMod>().GetTexture("MyTexture"),`. However (at least for me), it throws out an exception (yes, I've put the texture in my mod folder, yes I've changed "MyMod" into my mod's name). Fixing it is really easy, but took me like ten minutes of scrolling tmodloader documentation to figure out. Just remove the `GetInstance` part. It should look like this: `ModContent.GetTexture("MyTexture"),`.

I think the issue is because of some changes introduced in v0.11.7.5. This version changed a bit how Texture2D works.
(Also it could be because I've made this file directly in my mod folder, not in any subfolder I have no idea if that's the cause of this issue, but it could be. I don't really have patience, or time to test it, so I will leave that one for someone else to find out.)

**Comment by abluescarab** [comment]
Thanks for posting this issue when the wiki hadn't been updated. I've changed the code in the relevant wiki article and I'm closing this issue.
